General/General.WebUI/Models/CreateRole.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace General.WebUI.Models
{
    public class CreateRole
    {
       [Required]
        public string RoleName { get; set; }
    }
}

General/General.WebUI/Models/EditUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace General.WebUI.Models
{
    public class EditUser
    {
        public EditUser()
        {
            Roles = new List<string>();           

        }
        public string Id { get; set; }

        [Required]
        public string UserName { get; set; }
        [Required][EmailAddress]
        public string Email { get; set; }
        public IList<string> Roles { get; set; }

    }
}

General/General.WebUI/Controllers/ControlCenterController.cs
using General.Business.Abstrack;
using General.Entities;
using General.WebUI.Identity;
using General.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace General.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    [AutoValidateAntiforgeryToken]

    public class ControlCenterController : Controller
    {
        private IControlCenterService _controlCenterService;
        private SignInManager<ApplicationUser> _signInManager;
        private UserManager<ApplicationUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;
        public ControlCenterController(IControlCenterService controlCenterService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _controlCenterService = controlCenterService;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View(new ControlCenterModel()
            {
                CompanyServices = _controlCenterService.GetServicesAll(),
                ControlCenters = _controlCenterService.GetAll()

            });
        }
        public IActionResult OurServices()
        {
            return View(new ControlCenterModel()
            {
                CompanyServices = _controlCenterService.GetServicesAll(),
                ControlCenters = _controlCenterService.GetAll()

            });
        }
        // SERVİS EDİT SAYFASI
        public IActionResult ServiceDetail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var controlcenterId = _controlCenterService.GetDefault().Id;
            var entity = _controlCenterService.GetCompanyServicesById((int)id);

            var model = new CompanyServiceModel()

            {
                Id = entity.Id,
                name = entity.name,
                icon = entity.icon,
                image = entity.image,
                longexplanation = entity.longexplanation,
                shortexplanation = entity.shortexplanation,
                ControlCenterId = controlcenterId,

            };


            return View(model);

        }
        [HttpPost]
        [RequestFormLimits(MultipartBodyLengthLimit = 209715200)]
        public async Task<IActionResult> ServiceDetail(CompanyServiceModel model, IFormFile file)
        {
            var entity = _controlCenterService.GetCompanyServicesById(model.Id);
            if (entity == null)
            {
                return NotFound();
            }
            entity.name = model.name;
            entity.icon = model.icon;
            entity.longexplanation = model.longexplanation;
            entity.shortexplanation = model.shortexplanation;

            if (file != null)
            {
                string ImageUrl = entity.image;
                var deletepath1 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\services", ImageUrl);
                if (System.IO.File.Exists(deletepath1))
                {
                    System.IO.File.Delete(deletepath1);
                }
                entity.image = file.FileName;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\services", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);

                }


            }

            _controlCenterService.Update(entity);

            return RedirectToAction("Index");
        }
        public IActionResult ImageEditor()
        {
            return View();
        }
        public IActionResult CreateService()
        {
            return View(new CompanyServiceModel());
        }
        [HttpPost]
        [RequestFormLimits(MultipartBodyLengthLimit = 209715200)]

        public async Task<IActionResult> CreateService(CompanyServiceModel model, IFormFile file)
        {
            var controlcenterId = _controlCenterService.GetDefault().Id;

            if (!ModelState.IsValid)
            {

                var entity = new CompanyService()

                {

                    name = model.name,
                    icon = model.icon,
                    image = file.FileName,
                    longexplanation = model.longexplanation,
                    shortexplanation = model.shortexplanation,
                    ControlCenterId = controlcenterId,

                };

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\services", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                _controlCenterService.Create(entity);
                return RedirectToAction("Index");
            }
            return View(model);

        }
        [HttpPost]
        public IActionResult DeleteService(int serviceId)
        {
            var entity = _controlCenterService.GetCompanyServicesById(serviceId);
            if (entity != null)
            {
                _controlCenterService.Delete(entity);

            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        [RequestFormLimits(MultipartBodyLengthLimit = 209715200)]
        public async Task<IActionResult> EditControlCenterSettings(ControlCenterModel model, IFormFile logofile, IFormFile parallax1, IFormFile parallax2, IFormFile parallax3, IFormFile mainsliderimage, IFormFile mainsliderimage2, IFormFile mainsliderimage3, IFormFile mainsliderimage4)
        {

            var entity = _controlCenterService.GetDefault();
            if (entity == null)
            {
                return NotFound();
            }
            entity.contract1tr = model.contract1tr;
            entity.contract2tr = model.contract2tr;
            entity.contract3tr = model.contract3tr;
            entity.contract4tr = model.contract4tr;
            entity.socialnetwork1 = model.socialnetwork1;
            entity.socialnetwork2 = model.socialnetwork2;
            entity.socialnetwork3 = model.socialnetwork3;
            entity.socialnetwork4 = model.socialnetwork4;
            entity.Adress = model.Adress;
            entity.Phone = model.Phone;
            entity.Email = model.Email;
            entity.webadress = model.webadress;
            entity.Adress = model.Adress;
            entity.Phone = model.Phone;
            entity.Email = model.Email;
            entity.webadress = model.webadress;
            if (logofile != null)
            {
                string LogoUrl = entity.Logo;
                var deletepath1 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", LogoUrl);
                if (System.IO.File.Exists(deletepath1))
                {
                    System.IO.File.Delete(deletepath1);
                }
                entity.Logo = logofile.FileName;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", logofile.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await logofile.CopyToAsync(stream);
                }
            }
            if (mainsliderimage != null)
            {
                string LogoUrl = entity.Logo;
                var deletepath1 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\slider", LogoUrl);
                if (System.IO.File.Exists(deletepath1))
                {
                    System.IO.File.Delete(deletepath1);
                }
                entity.mainsliderimage = mainsliderimage.FileName;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\slider", mainsliderimage.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await mainsliderimage.CopyToAsync(stream);
                }
            }
            if (mainsliderimage2 != null)
            {
                string LogoUrl = entity.Logo;
                var deletepath1 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\slider", LogoUrl);
                if (System.IO.File.Exists(deletepath1))
                {
                    System.IO.File.Delete(deletepath1);
                }
                entity.mainsliderimage2 = mainsliderimage2.FileName;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\slider", mainsliderimage2.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await mainsliderimage2.CopyToAsync(stream);
                }
            }
            if (mainsliderimage3 != null)
            {
                string LogoUrl = entity.Logo;
                var deletepath1 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\slider", LogoUrl);
                if (System.IO.File.Exists(deletepath1))
                {
                    System.IO.File.Delete(deletepath1);
                }
                entity.mainsliderimage3 = mainsliderimage3.FileName;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\slider", mainsliderimage3.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await mainsliderimage3.CopyToAsync(stream);
                }
            }
            if (mainsliderimage4 != null)
            {
                string LogoUrl = entity.Logo;

General/General.WebUI/Views/ControlCenter/CreateRole.cshtml
@model CreateRole
@{
    ViewData["Title"] = "CreateRole";
    Layout = "~/Views/Shared/ControlCenter/_ControlCenterLayout.cshtml";
}

<section id="content">
    <section class="boxs">
        <div class="boxs-header">
            <h3 class="custom-font hb-blush">
                <strong>Bu sayfadan yeni servis hizmeti </strong> ekleyebilirsiniz.
            </h3>

        </div>
        <div class="boxs-body">
            <form class="form-horizontal" asp-action="CreateRole" asp-controller="ControlCenter" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="input01" class="col-sm-2 control-label">Rolün Adı:</label>
                    <div class="col-sm-10">
                        <input type="text"  asp-for="RoleName" value="" class="form-control" name="RoleName" id="input01" data-parsley-trigger="change" data-parsley-range="[3, 20]" required>
                        <span asp-validation-for="RoleName" class="help-block mb-0"></span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="reset" class="btn btn-raised btn-danger">İptal</button>
                        <button type="submit" class="btn btn-raised btn-default" id="form3Submit">Yeni Rol Oluştur</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>
<script src="~/js/jquery.js"></script>


<script>
    $(document).ready(function () {
        $(".alfa select").on("change", function () {
            var selVal = $(this).val();
            $('#input04').val(selVal);
        });

    });

</script>

General/General.WebUI/Views/ControlCenter/CreateService.cshtml
@model CompanyServiceModel
@{
    ViewData["Title"] = "CreateService";
    Layout = "~/Views/Shared/ControlCenter/_ControlCenterLayout.cshtml";
}

<section id="content">
    <section class="boxs">
        <div class="boxs-header">
            <h3 class="custom-font hb-blush">
                <strong>Bu sayfadan yeni servis hizmeti </strong> ekleyebilirsiniz.
            </h3>

        </div>
        <div class="boxs-body">
            <form class="form-horizontal" asp-action="CreateService" asp-controller="ControlCenter" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="input01" class="col-sm-2 control-label">Servisin Adı:</label>
                    <div class="col-sm-10">
                        <input type="text" value="" class="form-control" name="name" id="input01" data-parsley-trigger="change" data-parsley-range="[3, 20]" required>
                        <span asp-validation-for="name" class="help-block mb-0"></span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label for="input02" class="col-sm-2 control-label">Servisin Açıklaması Kısaca: </label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="input02" name="shortexplanation" data-parsley-trigger="change" required>
                        <span class="help-block mb-0">(Maksimim 100 karakterle servisinizi özetleyiniz.)</span>
                        <span asp-validation-for="shortexplanation" class="help-block mb-0"></span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label for="input03" class="col-sm-2 control-label">Servisin Açıklaması Uzun:</label>
                    <div class="col-sm-10">
                        <textarea type="text" class="form-control" id="summernote" name="longexplanation" data-parsley-trigger="change"></textarea>
                        <span class="help-block mb-0">(İstediğiniz uzunlukta bir açıklama yazabilirsiniz.)</span>
                        <span asp-validation-for="longexplanation" class="help-block mb-0"></span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label class="col-sm-2 control-label">Servisin İconu</label>
                    <div class="col-sm-10 alfa">
                        <select class="chosen-select " style="width: 240px;" name="se" data-parsley-trigger="change" required>
                            <option value="fa fa-dollar">Dolar</option>
                            <option value="fa fa-lightbulb-o">Ampul</option>
                            <option value="service-icon icon-pentagon">Şeffaf Kutu</option>
                            <option value="fa fa-bar-chart">Bar Grafiği</option>
                            <option value="fa fa-comments">Konuşma Baloncuğu</option>
                            <option value="fa fa-server">Server</option>
                            <option value="fa fa-camera">Camera</option>
                            <option value="fa fa-database">Database</option>
                            <option value="service-icon icon-pentagon">Kalkan</option>
                            <option value="fa fa-table">Tablo</option>
                            <option value="fa fa-pagelines">Yaprak</option>
                            <option value="fa fa-diamond">Elmas</option>
                            <option value="fa fa-users">Çoklu İnsan</option>
                            <option value="fa fa-desktop">Masaüstü Bilgisayar</option>

                        </select>
                    </div>
                    <span asp-validation-for="icon" class="help-block mb-0"></span>
                    <input type="hidden" class="form-control" id="input04" name="icon" value="@Model.icon">
                </div>

                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label class="col-sm-2 control-label"> Servisin Fotoğrafı</label>
                    <div class="col-sm-10">
                        <input type="hidden" name="image" value="@Model.image" />
                        <input type="file" class="filestyle" data-buttonText="Dosya bul." data-iconName="fa fa-inbox" name="file" value="@Model.image" required>
                        <span asp-validation-for="image" class="help-block mb-0"></span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="reset" class="btn btn-raised btn-danger">İptal</button>
                        <button type="submit" class="btn btn-raised btn-default" id="form3Submit">Kaydet ve Değiştir</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>
<script src="~/js/jquery.js"></script>


<script>
    $(document).ready(function () {
        $(".alfa select").on("change", function () {
            var selVal = $(this).val();
            $('#input04').val(selVal);
        });

    });

</script>

General/General.WebUI/Views/ControlCenter/EditUser.cshtml
@model EditUser
@{
    ViewData["Title"] = "EditUser";
    Layout = "~/Views/Shared/ControlCenter/_ControlCenterLayout.cshtml";
}

<section id="content">
    <section class="boxs">
        <div class="boxs-header">
            <h3 class="custom-font hb-blush">
                <strong>Bu sayfadan servisinizi </strong> düzenleyebilirsiniz.
            </h3>

        </div>
        <div class="boxs-body">
            <form class="form-horizontal" asp-action="EditUser" asp-controller="ControlCenter" method="post" enctype="multipart/form-data">
                <input type="hidden" name="userId" value="@Model.Id" />
                <div class="form-group">
                    <label for="input01" class="col-sm-2 control-label">Email Adresi:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="Email" id="input01" value="@Model.Email">
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label for="input01" class="col-sm-2 control-label">Kullanıcı Adı:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="UserName" id="input01" value="@Model.UserName">
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label class="col-sm-2 control-label">Kullanıcı Rolü</label>
                    <div class="col-sm-4">
                        @if (Model.Roles.Any())
                        {
                            foreach (var role in Model.Roles)
                            {
                                <input type="text" class="form-control" name="UserName" id="input01" value="@role" readonly>
                            }
                        }
                    </div>
                    <div class="col-sm-4">
                        <a asp-action="ManageUserRoles" asp-route-userId="@Model.Id"
                           class="btn btn-primary">
                            Rolü Düzenle
                        </a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="reset" class="btn btn-raised btn-danger">İptal</button>
                        <button type="submit" class="btn btn-raised btn-default">Kaydet ve Değiştir</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>

General/General.WebUI/Views/ControlCenter/OurServices.cshtml
@model General.WebUI.Models.ControlCenterModel

@{
    ViewData["Title"] = "OurServices";
    Layout = "~/Views/Shared/ControlCenter/_ControlCenterLayout.cshtml";
}

<section id="content">

    <div class="col-md-12">
        <div class="alert alert-danger">
            <div class="container-fluid">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="material-icons">X</i></span>
                </button>
                <b>Uyarı:</b> Bu sayfada yaptığınız değişiklikler sitenizin görünen tarafını etkilemektedir.
            </div>
        </div>



        <div class="alert alert-warning">
            <div class="container-fluid">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="material-icons">X</i></span>
                </button>
                <b>Dikkat:</b> Fotoğraflarınızı yeniden boyutlandırmak için sol tarafaki <a href="ControlCenter/ImageEditor">"Fotoğraf Editörü"</a>nü kullanabilirsiniz.
            </div>
        </div>




        <div class="boxs-body">
            <div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
                <ul class="nav nav-tabs" id="myTabs" role="tablist">

                    <li role="presentation" class="">
                        <a href="#services" role="tab" id="services-tab" data-toggle="tab" aria-controls="services" aria-expanded="false"><h3>Servislerimiz</h3></a>
                    </li>

                </ul>
                <div class="tab-content" id="myTabContent">
                    <!--Servisler--->
                    <div class="tab-pane fade active in" role="tabpanel" id="services" aria-labelledby="services-tab">
                        <section class="boxs">
                            <!-- boxs header -->
                            <div class="row">

                                <div class="col-sm-4 col-xs-6">
                                    <button class="btn btn-raised btn-success" type="submit"
                                            onclick="window.location='/ControlCenter/CreateService';" />Yeni Servis Ekle
                                </div>
                            </div>

                            <div class="boxs-body p-0">
                                <div class="table-responsive">
                                    <table class="table mb-0" id="usersList">
                                        <thead>
                                            <tr>

                                                <th>Servis Adı:</th>
                                                <th style="width:30px;">İşlem</th>
                                            </tr>
                                        </thead>
                                        <tbody>


                                            @foreach (var item in Model.CompanyServices)
                                            {
                                                <tr>

                                                    <td style="width:30px;">@item.name</td>
                                                    <td>
                                                        <button class="btn btn-warning btn-raised" onclick="window.location='/ControlCenter/ServiceDetail/@item.Id'">Düzenle</button>
                                                        <form asp-controller="ControlCenter" asp-action="DeleteService" method="post" style="display:inline;">
                                                            <input type="hidden" name="serviceId" value="@item.Id" />
                                                            <button class="btn btn-danger btn-raised" type="submit">Sil</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /boxs body -->


                        </section>

                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

General/General.WebUI/Views/ControlCenter/ServiceDetail.cshtml
@model CompanyServiceModel
@{
    ViewData["Title"] = "ServiceDetail";
    Layout = "~/Views/Shared/ControlCenter/_ControlCenterLayout.cshtml";
}

<section id="content">
    <section class="boxs">
        <div class="boxs-header">
            <h3 class="custom-font hb-blush">
                <strong>Bu sayfadan servisinizi </strong> düzenleyebilirsiniz.
            </h3>

        </div>
        <div class="boxs-body">
            <form class="form-horizontal" asp-action="ServiceDetail" asp-controller="ControlCenter" method="post" enctype="multipart/form-data">
                <input type="hidden" name="Id" value="@Model.Id"/>
                <div class="form-group">
                    <label for="input01" class="col-sm-2 control-label">Servisin Adı:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="name" id="input01" value="@Model.name">
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label for="input02" class="col-sm-2 control-label">Servisin Açıklaması Kısaca:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="input02" name="shortexplanation" value="@Model.shortexplanation">
                        <span class="help-block mb-0">(Maksimim 100 karakterle servisinizi özetleyiniz.)</span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label for="input03" class="col-sm-2 control-label">Servisin Açıklaması Uzun:</label>
                    <div class="col-sm-10">
                        <textarea type="text" class="form-control" id="summernote" name="longexplanation">@Model.longexplanation</textarea>
                        <span class="help-block mb-0">(İstediğiniz uzunlukta bir açıklama yazabilirsiniz.)</span>
                        <span asp-validation-for="longexplanation" class="help-block mb-0"></span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label class="col-sm-2 control-label">Servisin İconu</label>
                    <div class="col-sm-10 alfa">
                        <select class="chosen-select " style="width: 240px;" name="se">
                            <option value="fa fa-dollar">Dolar</option>
                            <option value="fa fa-lightbulb-o">Ampul</option>
                            <option value="service-icon icon-pentagon">Şeffaf Kutu</option>
                            <option value="fa fa-bar-chart">Bar Grafiği</option>
                            <option value="fa fa-comments">Konuşma Baloncuğu</option>
                            <option value="fa fa-server">Server</option>
                            <option value="fa fa-camera">Camera</option>
                            <option value="fa fa-database">Database</option>
                            <option value="service-icon icon-pentagon">Kalkan</option>
                            <option value="fa fa-table">Tablo</option>
                            <option value="fa fa-pagelines">Yaprak</option>
                            <option value="fa fa-diamond">Elmas</option>
                            <option value="fa fa-users">Çoklu İnsan</option>
                            <option value="fa fa-desktop">Masaüstü Bilgisayar</option>

                        </select>
                    </div>
                    <input type="hidden" class="form-control" id="input04" name="icon" value="@Model.icon">
                </div>

                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <label class="col-sm-2 control-label"> Servisin Fotoğrafı</label>
                    <div class="col-sm-10">
                        <label>Ürün Görseli</label>
                        <input type="hidden" name="image" value="@Model.image" />
                        <img src="~/images/services/@Model.image" alt="Servisin Fotoğrafı" style="width:80px; height:120px;" />
                        <input type="file" class="filestyle" data-buttonText="Dosya bul." data-iconName="fa fa-inbox" name="file">
                        <span asp-validation-for="image" class="help-block mb-0"></span>
                    </div>
                </div>
                <hr class="line-dashed full-witdh-line" />
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="reset" class="btn btn-raised btn-danger">İptal</button>
                        <button type="submit" class="btn btn-raised btn-default">Kaydet ve Değiştir</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>
<script src="~/js/jquery.js"></script>
<script>
    $(document).ready(function () {
        $(".alfa select").on("change", function () {
            var selVal = $(this).val();
            $('#input04').val(selVal);
        });

    });
</script>